### ISSUE TITLE
Error when connected to host network

### ISSUE THREAD

**Issue by osegarra** [MI-OSiRIS/docker-nfs-ganesha-ceph#1]
Hi, 

If I execute the docker with my overlay network. It works perfectly but If I run it with the host network it fails (note I have made some changes to let the script retrieve the ceph_monitors from the ceph.conf file)

docker service create -d --name vdicube_pub_ceph_nfs \
--network=host \
--mount type=bind,source=/etc/ceph,destination=/etc/ceph \
--mount type=bind,source=/etc/localtime,destination=/etc/localtime,readonly \
-e GANESHA_EXPORT=/ \
-e GANESHA_SQUASH=No_Root_Squash \
-e CEPH_FS_PATH=/ \
--mode=global \
--constraint node.labels.nfs==1 \
--hostname=vdicube_pub_ceph_nfs \
vdicube/ceph_nfs

The log:

Bootstrapping Ganesha NFS config,
Bootstrapping CA cert,
otstrapping idmap config,
Starting rpc services,
Starting sssd,
Starting dbus,
Starting Ganesha NFS,
26/01/2019 15:33:30 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] main :MAIN :EVENT :ganesha.nfsd Starting: Ganesha Version 2.7.1,
26/01/2019 15:33:30 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed,
26/01/2019 15:33:30 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.,
ganesha.nfsd: conf_parse_line: 2: missing value in assignment,
26/01/2019 15:33:31 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.,
26/01/2019 15:33:31 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 90,
26/01/2019 15:33:31 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] lower_my_caps :NFS STARTUP :EVENT :CAP_SYS_RESOURCE was successfully removed for proper quota management in FSAL,
26/01/2019 15:33:31 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] lower_my_caps :NFS STARTUP :EVENT :currenty set capabilities are: = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+eip,
26/01/2019 15:33:31 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_Init_svc :DISP :CRIT :Cannot acquire credentials for principal nfs,
26/01/2019 15:33:31 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_Init_admin_thread :NFS CB :EVENT :Admin thread initialized,
26/01/2019 15:33:31 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_rpc_cb_init_ccache :NFS STARTUP :EVENT :Callback creds directory (/var/run/ganesha) already exists,
26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_rpc_cb_init_ccache :NFS STARTUP :WARN :gssd_refresh_krb5_machine_credential failed (-1765328160:0),
26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_Start_threads :THREAD :EVENT :Starting delayed executor.,
26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_Start_threads :THREAD :EVENT :9P/TCP dispatcher thread was started successfully,
26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_Start_threads :THREAD :EVENT :gsh_dbusthread was started successfully,
26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_Start_threads :THREAD :EVENT :admin thread was started successfully,
26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_Start_threads :THREAD :EVENT :reaper thread was started successfully,
26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_Start_threads :THREAD :EVENT :General fridge was started successfully,
26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[_9p_disp] _9p_dispatcher_thread :9P DISP :EVENT :9P dispatcher started,
**26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] rpc :TIRPC :EVENT :svc_rqst_hook_events: 0x4e1c9a0 fd 1024 xp_refcnt 1 sr_rec 0x4d9bfd0 evchan 2 ev_refcnt 3 epoll_fd 37 control fd pair (35:36) hook failed (9),
26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nsm_connect :NLM :CRIT :connect to statd failed: RPC: Unknown protocol,
26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nsm_unmonitor_all :NLM :CRIT :Unmonitor all nsm_connect failed,**
26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------,
26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_start :NFS STARTUP :EVENT :             NFS SERVER INITIALIZED,
26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------,
26/01/2019 15:35:03 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE,

**Comment by bmeekhof** [comment]
We use the container with host networking so I'd expect it to work.  I think that you need to include at least the '-P' flag to publish ports and also '-p 2049:2049' to expose the NFSv4 port at the expected place.    More info:  https://docs.docker.com/engine/reference/run/#expose-incoming-ports

**Comment by osegarra** [comment]
Hi, 

I think it is not compatible using the host network with port publishing. If you try to expose a port with the host network docker raises an error due to this incompatibility.

I don't know if the port publish has relation with the error detected:

> 26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] rpc :TIRPC :EVENT :svc_rqst_hook_events: 0x4e1c9a0 fd 1024 xp_refcnt 1 sr_rec 0x4d9bfd0 evchan 2 ev_refcnt 3 epoll_fd 37 control fd pair (35:36) hook failed (9),
> 26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nsm_connect :NLM :CRIT :connect to statd failed: RPC: Unknown protocol,
> 26/01/2019 15:33:33 : epoch 5c4c6fba : vdicube_pub_ceph_nfs : ganesha.nfsd-38[main] nsm_unmonitor_all :NLM :CRIT :Unmonitor all nsm_connect failed,

Thanks a lot in advance

**Comment by bmeekhof** [comment]
You're right, my mistake, I see the same warning about publishing ports.  I'm afraid I can't really say what the issue is here, especially since it sounds like you have made some changes to the container?  We are running exactly this container with host based networking and have not seen a similar issue.  

If you can point me at a public link to your revised container I will at least take a look and see if there is anything obvious that might be causing the problem.

**Comment by osegarra** [comment]
Hi, you can try it with: 

docker service create -d --name vdicube_pub_ceph_nfs \
--network=host \
--mount type=bind,source=/etc/ceph,destination=/etc/ceph \
--mount type=bind,source=/etc/localtime,destination=/etc/localtime,readonly \
-e GANESHA_EXPORT=/ \
-e GANESHA_SQUASH=No_Root_Squash \
-e CEPH_FS_PATH=/ \
-e GANESHA_ACCESS_TYPE="RO" \
--replicas=1 \
--hostname=vdicube_pub_ceph_nfs \
vdicube/ceph_nfs

Thanks a lot!

**Comment by bmeekhof** [comment]
Unfortunately running and debugging your container is a bit outside the scope of support I'm able to provide here.  If you do find some issue specific to our container and want to put in a suggestion for a fix or pull request we'll certainly take a look at it.  Since this appears to be related to a fork/modification of our container I'm going to close out the issue.

**Comment by osegarra** [comment]
Thanks a lot!
